"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BookOpen, CalendarDays, Check, ChevronRight, ClipboardCheck, ClipboardList, CreditCard, DollarSign, Filter, LayoutDashboard, LogOut, Plus, RefreshCw, Search, Settings2, ShieldCheck, Trash2, UserPlus, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Tab = "overview"|"students"|"groups"|"courses"|"attendance"|"payments"|"leads"|"staff"|"schedule"|"reports"|"access";
type Student = { id:string; full_name:string; email:string|null; phone:string|null; role:string; rating_points:number; status:string; city:string|null; birth_date:string|null; address:string|null; started_at:string|null; notes:string|null; avatar_url:string|null };
type Group = { id:string; name:string; course:string; level:string; capacity:number; active:boolean };
type Course = { id:string; name:string; code:string|null; duration_months:number; price:number; active:boolean };
type Lead = { id:string; application_number:string; full_name:string; email:string|null; phone:string; course:string; status:string; created_at:string; admin_note:string|null };
type Payment = { id:string; student_id:string; amount:number; payment_date:string; method:string; status:string; receipt_no:string|null; note:string|null; student?:{full_name:string}[]|null };
type Attendance = { id:string; student_id:string; group_id:string|null; attendance_date:string; status:string; note:string|null; student?:{full_name:string}[]|null };

const supabase=createClient();
const roles=["student","mentor","manager","admin","super_admin"];
const leadStatuses={new:"Yangi",contacted:"Bog‘lanildi",interview:"Suhbat",accepted:"Qabul qilindi",rejected:"Rad etildi",studying:"O‘qimoqda",completed:"Tugatdi"};

export default function Admin(){
 const router=useRouter(); const [session,setSession]=useState<any>(null); const [checking,setChecking]=useState(true); const [tab,setTab]=useState<Tab>("overview"); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 const [students,setStudents]=useState<Student[]>([]); const [groups,setGroups]=useState<Group[]>([]); const [courses,setCourses]=useState<Course[]>([]); const [leads,setLeads]=useState<Lead[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [attendance,setAttendance]=useState<Attendance[]>([]); const [staff,setStaff]=useState<Student[]>([]); const [events,setEvents]=useState<any[]>([]); const [query,setQuery]=useState("");
 const [selected,setSelected]=useState<Student|null>(null); const [showStudent,setShowStudent]=useState(false); const [showCreate,setShowCreate]=useState(false); const [showGroup,setShowGroup]=useState(false); const [showCourse,setShowCourse]=useState(false); const [showPayment,setShowPayment]=useState(false); const [showAttendance,setShowAttendance]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(!data.session){setChecking(false);return}const {data:isAdmin}=await supabase.rpc("is_admin");if(!isAdmin){await supabase.auth.signOut();setError("Bu hisob CRM huquqiga ega emas.");setChecking(false);return}setSession(data.session);await load();setChecking(false)})},[]);
 async function load(){setLoading(true);setError(""); const [s,g,c,l,p,att,st,e]=await Promise.all([
  supabase.from("profiles").select("id,full_name,email,phone,role,rating_points,status,city,birth_date,address,started_at,notes,avatar_url").order("created_at",{ascending:false}),
  supabase.from("groups").select("*").order("created_at",{ascending:false}),supabase.from("courses").select("*").order("created_at",{ascending:false}),
  supabase.from("applications").select("id,application_number,full_name,email,phone,course,status,created_at,admin_note").order("created_at",{ascending:false}),
  supabase.from("payments").select("id,student_id,course_id,amount,payment_date,method,status,receipt_no,note,student:profiles!payments_student_id_fkey(full_name),course:courses!payments_course_id_fkey(name)").order("payment_date",{ascending:false}).limit(200),
  supabase.from("attendance").select("id,student_id,group_id,attendance_date,status,note,student:profiles!attendance_student_id_fkey(full_name)").order("attendance_date",{ascending:false}).limit(200),
  supabase.from("profiles").select("id,full_name,email,phone,role,rating_points,status,city,birth_date,address,started_at,notes,avatar_url").in("role",["mentor","manager","admin","super_admin"]),
  supabase.from("schedule_events").select("*,group:groups!schedule_events_group_id_fkey(name),mentor:profiles!schedule_events_mentor_id_fkey(full_name)").order("starts_at",{ascending:true}).limit(100)
 ]); const errs=[s,g,c,l,p,att,st,e].find(x=>x.error); if(errs)setError(errs.error?.message||""); setStudents((s.data||[]).filter((x:any)=>x.role==="student")); setGroups(g.data||[]);setCourses(c.data||[]);setLeads(l.data||[]);setPayments(p.data||[]);setAttendance(att.data||[]);setStaff(st.data||[]);setEvents(e.data||[]);setLoading(false); }
 async function logout(){await supabase.auth.signOut();router.replace("/")}
 if(checking)return <div className="page-loader"><div className="loader-mark">N</div><span>CRM tekshirilmoqda...</span></div>;
 if(!session)return <main className="auth-page"><div className="auth-shell admin-login"><a href="/" className="logo auth-logo">NOVA <span>ACADEMY</span></a><div className="auth-card"><div className="auth-card-icon"><ShieldCheck/></div><div className="eyebrow">SECURE CRM ACCESS</div><h2>Admin CRM</h2><p className="muted">CRM'ga kirish uchun mavjud admin hisobingizdan foydalaning.</p><a className="btn primary btn-lg" style={{width:"100%",marginTop:18}} href="/login">Login sahifasiga o‘tish <ArrowUpRight size={16}/></a></div></div></main>;
 const newLeads=leads.filter(x=>x.status==="new").length; const month=new Date().toISOString().slice(0,7); const revenue=payments.filter(x=>x.status==="paid"&&x.payment_date.startsWith(month)).reduce((a,x)=>a+Number(x.amount),0); const debtors=0; const filtered=students.filter(s=>!query||`${s.full_name} ${s.phone||""} ${s.email||""} ${s.city||""}`.toLowerCase().includes(query.toLowerCase()));
 const nav:[Tab,string,any][]=[["overview","Dashboard",LayoutDashboard],["students","O‘quvchilar",Users],["groups","Guruhlar",Users],["courses","Kurslar",BookOpen],["attendance","Davomat",ClipboardCheck],["payments","To‘lovlar",CreditCard],["leads","Arizalar",ClipboardList],["staff","Mentorlar / xodimlar",ShieldCheck],["schedule","Jadval",CalendarDays],["reports","Hisobotlar",DollarSign],["access","RBAC / Ruxsatlar",Settings2]];
 return <main className="crm-page"><header className="crm-nav"><div className="crm-brand"><a className="logo" href="/">NOVA <span>ACADEMY</span></a><b>PRO CRM</b></div><div className="crm-actions"><span className="admin-online"><i/> Online</span><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={16}/></button><button className="btn" onClick={logout}><LogOut size={15}/> Chiqish</button></div></header><div className="crm-layout"><aside className="crm-sidebar"><div className="side-label">NOVA MANAGEMENT</div>{nav.map(([id,label,Icon])=><button key={id} className={`side-link ${tab===id?"active":""}`} onClick={()=>setTab(id)}><Icon/><span>{label}</span>{id==="leads"&&newLeads>0?<em>{newLeads}</em>:<ChevronRight size={14}/>}</button>)}<div className="crm-sidebar-foot"><span>NOVA ACADEMY</span><small>Learning · CRM · Growth</small></div></aside><section className="crm-content">{error&&<div className="crm-alert">{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}
 {tab==="overview"&&<Overview students={students} groups={groups} leads={leads} payments={payments} attendance={attendance} revenue={revenue} newLeads={newLeads} onStudents={()=>setTab("students")} onLeads={()=>setTab("leads")}/>} 
 {tab==="students"&&<Students students={filtered} query={query} setQuery={setQuery} onAdd={()=>setShowCreate(true)} onOpen={(s)=>{setSelected(s);setShowStudent(true)}}/>}
 {tab==="groups"&&<Groups groups={groups} students={students} onAdd={()=>setShowGroup(true)} onRefresh={load}/>} {tab==="courses"&&<Courses courses={courses} onAdd={()=>setShowCourse(true)}/>} {tab==="attendance"&&<AttendancePage rows={attendance} students={students} groups={groups} onAdd={()=>setShowAttendance(true)}/>} {tab==="payments"&&<PaymentsPage rows={payments} students={students} onAdd={()=>setShowPayment(true)}/>} {tab==="leads"&&<Leads leads={leads} onRefresh={load}/>} {tab==="staff"&&<Staff staff={staff}/>} {tab==="schedule"&&<Schedule events={events} groups={groups} staff={staff}/>} {tab==="reports"&&<Reports students={students} groups={groups} payments={payments} attendance={attendance}/>} {tab==="access"&&<Access staff={staff}/>}</section></div>{showCreate&&<CreateStudent courses={courses} groups={groups} onClose={()=>setShowCreate(false)} onSaved={async()=>{setShowCreate(false);await load()}}/>}{showStudent&&selected&&<StudentDrawer student={selected} groups={groups} courses={courses} onClose={()=>setShowStudent(false)} onSaved={async()=>{setShowStudent(false);await load()}}/>}{showGroup&&<CreateGroup courses={courses} onClose={()=>setShowGroup(false)} onSaved={async()=>{setShowGroup(false);await load()}}/>}{showCourse&&<CreateCourse onClose={()=>setShowCourse(false)} onSaved={async()=>{setShowCourse(false);await load()}}/>}{showPayment&&<CreatePayment students={students} courses={courses} onClose={()=>setShowPayment(false)} onSaved={async()=>{setShowPayment(false);await load()}}/>}{showAttendance&&<CreateAttendance students={students} groups={groups} onClose={()=>setShowAttendance(false)} onSaved={async()=>{setShowAttendance(false);await load()}}/>}</main>
}

function Head({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub?:string;action?:React.ReactNode}){return <div className="crm-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{sub&&<p className="muted">{sub}</p>}</div>{action}</div>}
function Overview({students,groups,leads,payments,attendance,revenue,newLeads,onStudents,onLeads}:{students:Student[];groups:Group[];leads:Lead[];payments:Payment[];attendance:Attendance[];revenue:number;newLeads:number;onStudents:()=>void;onLeads:()=>void}){const present=attendance.filter(a=>a.status==="present").length;const attRate=attendance.length?Math.round(present/attendance.length*100):0;return <><Head eyebrow="COMMAND CENTER" title="Bugungi holat." sub="NOVA ACADEMY operatsiyalarini bitta professional markazdan boshqaring."/><div className="crm-metrics"><Metric label="Jami o‘quvchilar" value={students.length} icon={<Users/>}/><Metric label="Faol guruhlar" value={groups.filter(g=>g.active).length} icon={<BookOpen/>}/><Metric label="Yangi arizalar" value={newLeads} icon={<ClipboardList/>}/><Metric label="Oy tushumi" value={`${revenue.toLocaleString("uz-UZ")} so‘m`} icon={<DollarSign/>}/></div><div className="crm-grid-two"><div className="crm-panel"><PanelHead title="Admission pipeline" action={<button className="text-link" onClick={onLeads}>Barchasi <ArrowUpRight size={14}/></button>}/><div className="pipeline">{Object.entries(leadStatuses).map(([k,v])=><div key={k}><span>{v}</span><strong>{leads.filter(x=>x.status===k).length}</strong></div>)}</div></div><div className="crm-panel"><PanelHead title="Academy health"/><div className="health-grid"><MetricSmall label="Davomat" value={`${attRate}%`}/><MetricSmall label="To‘lovlar" value={payments.length}/><MetricSmall label="Guruhlar" value={groups.length}/><MetricSmall label="Studentlar" value={students.length}/></div></div></div><div className="crm-panel" style={{marginTop:12}}><PanelHead title="Tezkor amallar"/><div className="quick-actions"><button className="btn primary" onClick={onStudents}><UserPlus size={15}/> O‘quvchi boshqaruvi</button><button className="btn" onClick={onLeads}><ClipboardList size={15}/> Arizalarni ko‘rish</button></div></div></>}
function Metric({label,value,icon}:{label:string;value:any;icon:any}){return <div className="crm-metric"><div>{icon}</div><span>{label}</span><strong>{value}</strong></div>};function MetricSmall({label,value}:{label:string;value:any}){return <div className="health-item"><span>{label}</span><strong>{value}</strong></div>};function PanelHead({title,action}:{title:string;action?:React.ReactNode}){return <div className="panel-head"><div><div className="eyebrow">NOVA CRM</div><h3>{title}</h3></div>{action}</div>}
function Students({students,query,setQuery,onAdd,onOpen}:{students:Student[];query:string;setQuery:(v:string)=>void;onAdd:()=>void;onOpen:(s:Student)=>void}){return <><Head eyebrow="STUDENT MANAGEMENT" title="O‘quvchilar." sub="Har bir o‘quvchi uchun yagona CRM profil, kurs, guruh, davomat va to‘lov tarixini boshqaring." action={<button className="btn primary" onClick={onAdd}><Plus size={15}/> O‘quvchi qo‘shish</button>}/><div className="crm-panel filters"><div className="searchbox"><Search size={16}/><input placeholder="Ism, telefon, email, shahar..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="filter-info"><Filter size={14}/> {students.length} ta profil</span></div><div className="crm-panel table-panel"><div className="table-wrap"><table><thead><tr><th>O‘quvchi</th><th>Kontakt</th><th>Holat</th><th>Rating</th><th>Shahar</th><th></th></tr></thead><tbody>{students.map(s=><tr key={s.id} onClick={()=>onOpen(s)}><td><div className="student-cell"><div className="avatar">{s.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><b>{s.full_name}</b></div></td><td><b>{s.phone||"—"}</b><small>{s.email||"—"}</small></td><td><span className="status status-studying">{s.status||"active"}</span></td><td><strong className="xp">{s.rating_points} XP</strong></td><td>{s.city||"—"}</td><td><button className="small-action">Profil <ChevronRight size={14}/></button></td></tr>)}{!students.length&&<tr><td colSpan={6} className="empty-table">O‘quvchilar topilmadi.</td></tr>}</tbody></table></div></div></>}
function Groups({groups,students,onAdd,onRefresh}:{groups:Group[];students:Student[];onAdd:()=>void;onRefresh:()=>void}){return <><Head eyebrow="GROUP MANAGEMENT" title="Guruhlar." sub="Kurs, daraja, sig‘im va o‘quvchilar tarkibini boshqaring." action={<button className="btn primary" onClick={onAdd}><Plus size={15}/> Guruh yaratish</button>}/><div className="crm-card-grid">{groups.map(g=><div className="crm-panel group-card" key={g.id}><div className="group-top"><span className="status status-new">{g.active?"ACTIVE":"PAUSED"}</span><BookOpen size={17}/></div><h3>{g.name}</h3><p>{g.course} · {g.level}</p><div className="group-stats"><span>Sig‘im <b>{g.capacity}</b></span><span>O‘quvchi <b>{students.filter(s=>false).length}+</b></span></div></div>)}{!groups.length&&<div className="crm-panel">Guruhlar hali yo‘q.</div>}</div></>}
function Courses({courses,onAdd}:{courses:Course[];onAdd:()=>void}){return <><Head eyebrow="COURSE CATALOG" title="Kurslar." sub="Kurs katalogi, davomiylik va narxlarni boshqaring." action={<button className="btn primary" onClick={onAdd}><Plus size={15}/> Kurs qo‘shish</button>}/><div className="crm-card-grid">{courses.map(c=><div className="crm-panel group-card" key={c.id}><div className="group-top"><span className="status status-new">{c.active?"ACTIVE":"INACTIVE"}</span><BookOpen size={17}/></div><h3>{c.name}</h3><p>{c.code||"NOVA"} · {c.duration_months} oy</p><strong className="course-price">{Number(c.price).toLocaleString("uz-UZ")} so‘m</strong></div>)}</div></>}
function AttendancePage({rows,students,groups,onAdd}:{rows:Attendance[];students:Student[];groups:Group[];onAdd:()=>void}){return <><Head eyebrow="ATTENDANCE" title="Davomat." sub="Keldi, kelmadi, kechikdi yoki uzrli holatlarni tarix bilan saqlang." action={<button className="btn primary" onClick={onAdd}><Plus size={15}/> Davomat kiritish</button>}/><div className="crm-panel table-panel"><div className="table-wrap"><table><thead><tr><th>Sana</th><th>O‘quvchi</th><th>Holat</th><th>Izoh</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.attendance_date}</td><td><b>{(r as any).student?.full_name||students.find(s=>s.id===r.student_id)?.full_name||"—"}</b></td><td><span className={`status ${r.status==="present"?"status-studying":r.status==="late"?"status-new":"status-rejected"}`}>{r.status}</span></td><td>{r.note||"—"}</td></tr>)}</tbody></table></div></div></>}
function PaymentsPage({rows,students,onAdd}:{rows:Payment[];students:Student[];onAdd:()=>void}){const total=rows.filter(x=>x.status==="paid").reduce((a,x)=>a+Number(x.amount),0);return <><Head eyebrow="FINANCE" title="To‘lovlar." sub="To‘lovlar, kvitansiyalar va moliyaviy tarixni boshqaring." action={<button className="btn primary" onClick={onAdd}><Plus size={15}/> To‘lov kiritish</button>}/><div className="crm-metrics"><Metric label="Jami tushum" value={`${total.toLocaleString("uz-UZ")} so‘m`} icon={<DollarSign/>}/><Metric label="Tranzaksiyalar" value={rows.length} icon={<CreditCard/>}/></div><div className="crm-panel table-panel" style={{marginTop:12}}><div className="table-wrap"><table><thead><tr><th>Sana</th><th>O‘quvchi</th><th>Summa</th><th>Usul</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.payment_date}</td><td>{(r as any).student?.full_name||students.find(s=>s.id===r.student_id)?.full_name||"—"}</td><td><strong>{Number(r.amount).toLocaleString("uz-UZ")} so‘m</strong></td><td>{r.method}</td><td><span className="status status-studying">{r.status}</span></td></tr>)}</tbody></table></div></div></>}
function Leads({leads,onRefresh}:{leads:Lead[];onRefresh:()=>void}){async function update(id:string,status:string){const {error}=await supabase.from("applications").update({status}).eq("id",id);if(error)alert(error.message);else onRefresh()}return <><Head eyebrow="ADMISSIONS / LEADS" title="Arizalar." sub="Lead → suhbat → qabul → o‘quvchi jarayonini boshqaring."/><div className="crm-card-grid lead-grid">{leads.map(l=><div className="crm-panel" key={l.id}><div className="lead-head"><span className={`status status-${l.status}`}>{leadStatuses[l.status as keyof typeof leadStatuses]||l.status}</span><span className="mono">{l.application_number}</span></div><h3>{l.full_name}</h3><p>{l.phone} · {l.email||"email yo‘q"}</p><small>{l.course}</small><div className="lead-actions">{Object.entries(leadStatuses).slice(0,5).map(([k,v])=><button key={k} className="small-action" onClick={()=>update(l.id,k)}>{v}</button>)}</div></div>)}</div></>}
function Staff({staff}:{staff:Student[]}){return <><Head eyebrow="PEOPLE" title="Mentorlar va xodimlar." sub="Xodim profili va CRM rollarini ko‘ring."/><div className="crm-card-grid">{staff.map(s=><div className="crm-panel group-card" key={s.id}><div className="student-cell"><div className="avatar">{s.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h3>{s.full_name}</h3><p>{s.role}</p></div></div><div className="drawer-grid" style={{marginTop:18}}><div><span>Telefon</span><strong>{s.phone||"—"}</strong></div><div><span>Email</span><strong>{s.email||"—"}</strong></div></div></div>)}</div></>}
function Schedule({events}:{events:any[];groups:Group[];staff:Student[]}){return <><Head eyebrow="ACADEMIC CALENDAR" title="Jadval." sub="Guruh va mentor darslarini markazlashtirilgan kalendarda boshqaring."/><div className="crm-panel table-panel"><div className="table-wrap"><table><thead><tr><th>Vaqt</th><th>Dars</th><th>Guruh</th><th>Mentor</th><th>Xona</th><th>Status</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.starts_at).toLocaleString("uz-UZ")}</td><td><b>{e.title}</b></td><td>{e.group?.name||"—"}</td><td>{e.mentor?.full_name||"—"}</td><td>{e.room||"—"}</td><td>{e.status}</td></tr>)}</tbody></table></div></div></>}
function Reports({students,groups,payments,attendance}:{students:Student[];groups:Group[];payments:Payment[];attendance:Attendance[]}){const paid=payments.filter(p=>p.status==="paid").reduce((a,p)=>a+Number(p.amount),0);const present=attendance.filter(a=>a.status==="present").length;return <><Head eyebrow="ANALYTICS" title="Hisobotlar." sub="CRM ma’lumotlari asosida operatsion ko‘rsatkichlar."/><div className="crm-metrics"><Metric label="O‘quvchilar" value={students.length} icon={<Users/>}/><Metric label="Guruhlar" value={groups.length} icon={<BookOpen/>}/><Metric label="Tushum" value={`${paid.toLocaleString("uz-UZ")} so‘m`} icon={<DollarSign/>}/><Metric label="Davomat" value={attendance.length?`${Math.round(present/attendance.length*100)}%`:"0%"} icon={<ClipboardCheck/>}/></div><div className="crm-panel report-list"><div><span>Faol o‘quvchilar</span><strong>{students.filter(s=>s.status==="active").length}</strong></div><div><span>Faol guruhlar</span><strong>{groups.filter(g=>g.active).length}</strong></div><div><span>Paid tranzaksiyalar</span><strong>{payments.filter(p=>p.status==="paid").length}</strong></div></div></>}
function Access({staff}:{staff:Student[]}){return <><Head eyebrow="RBAC" title="Ruxsatlar." sub="Super Admin, Admin, Manager, Mentor va Student rollari."/><div className="crm-card-grid">{roles.map(r=><div className="crm-panel role-card" key={r}><ShieldCheck size={18}/><h3>{r}</h3><p>{r==="super_admin"?"To‘liq tizim nazorati":r==="admin"?"CRM va ma’lumotlar boshqaruvi":r==="manager"?"Operatsion boshqaruv":r==="mentor"?"Guruh va akademik jarayon": "Faqat o‘z profili va ta’lim ma’lumotlari"}</p></div>)}</div></>}

function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="drawer-backdrop"><aside className="drawer crm-modal"><div className="drawer-head"><div><div className="eyebrow">NOVA CRM</div><h2>{title}</h2></div><button className="close" onClick={onClose}><X/></button></div><div className="drawer-body">{children}</div></aside></div>}
function CreateStudent({courses,groups,onClose,onSaved}:{courses:Course[];groups:Group[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({});const [saving,setSaving]=useState(false);async function save(e:any){e.preventDefault();setSaving(true);const r=await fetch("/api/admin/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const j=await r.json();setSaving(false);if(!r.ok){alert(j.error||"Xatolik");return}await onSaved()}return <Modal title="Yangi o‘quvchi profili" onClose={onClose}><form onSubmit={save}><FormInput label="Ism va familiya *" value={f.full_name||""} onChange={(v)=>setF({...f,full_name:v})} required/><FormInput label="Email *" type="email" value={f.email||""} onChange={(v)=>setF({...f,email:v})} required/><FormInput label="Vaqtinchalik parol *" type="password" value={f.password||""} onChange={(v)=>setF({...f,password:v})} required placeholder="Kamida 8 belgi"/><FormInput label="Telefon" value={f.phone||""} onChange={(v)=>setF({...f,phone:v})}/><div className="drawer-grid"><FormSelect label="Kurs" value={f.course_id||""} options={courses.map(c=>[c.id,c.name])} onChange={(v)=>setF({...f,course_id:v})}/><FormSelect label="Guruh" value={f.group_id||""} options={groups.map(g=>[g.id,g.name])} onChange={(v)=>setF({...f,group_id:v})}/><FormInput label="Tug‘ilgan sana" type="date" value={f.birth_date||""} onChange={(v)=>setF({...f,birth_date:v})}/><FormInput label="Boshlanish sanasi" type="date" value={f.started_at||""} onChange={(v)=>setF({...f,started_at:v})}/></div><FormInput label="Shahar" value={f.city||""} onChange={(v)=>setF({...f,city:v})}/><FormInput label="Manzil" value={f.address||""} onChange={(v)=>setF({...f,address:v})}/><div className="field"><label>Izoh</label><textarea value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/></div><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}} disabled={saving}>{saving?"Yaratilmoqda...":"Profilni yaratish"}<Check size={16}/></button></form></Modal>}
function StudentDrawer({student,onClose,onSaved}:{student:Student;groups:Group[];courses:Course[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState(student);const [saving,setSaving]=useState(false);async function save(){setSaving(true);const {error}=await supabase.from("profiles").update({full_name:f.full_name,email:f.email,phone:f.phone,birth_date:f.birth_date,city:f.city,address:f.address,started_at:f.started_at,status:f.status,notes:f.notes,avatar_url:f.avatar_url,updated_at:new Date().toISOString()}).eq("id",f.id);setSaving(false);if(error)alert(error.message);else await onSaved()}return <Modal title={f.full_name} onClose={onClose}><div className="profile-hero"><div className="avatar avatar-lg">{f.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><div className="eyebrow">STUDENT PROFILE</div><h3>{f.full_name}</h3><p>{f.role} · {f.status}</p></div></div><div className="drawer-grid"><FormInput label="Ism va familiya" value={f.full_name} onChange={v=>setF({...f,full_name:v})}/><FormInput label="Telefon" value={f.phone||""} onChange={v=>setF({...f,phone:v})}/><FormInput label="Email" value={f.email||""} onChange={v=>setF({...f,email:v})}/><FormInput label="Tug‘ilgan sana" type="date" value={f.birth_date||""} onChange={v=>setF({...f,birth_date:v})}/><FormInput label="Shahar" value={f.city||""} onChange={v=>setF({...f,city:v})}/><FormSelect label="Holat" value={f.status||"active"} options={[["active","Faol"],["frozen","Muzlatilgan"],["completed","Tugatgan"],["removed","Chiqarilgan"]]} onChange={v=>setF({...f,status:v})}/></div><div className="profile-tabs"><span>Davomat</span><span>To‘lovlar</span><span>Baholar</span><span>Topshiriqlar</span><span>Sertifikat</span><span>Activity</span></div><div className="field"><label>Manzil</label><input value={f.address||""} onChange={e=>setF({...f,address:e.target.value})}/></div><div className="field" style={{marginTop:14}}><label>Izohlar</label><textarea value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/></div><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}} onClick={save} disabled={saving}>{saving?"Saqlanmoqda...":"Profilni saqlash"}<Check size={16}/></button></Modal>}
function CreateGroup({courses,onClose,onSaved}:{courses:Course[];onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState("");const [course,setCourse]=useState(courses[0]?.name||"");const [level,setLevel]=useState("Beginner");const [capacity,setCapacity]=useState("20");async function save(e:any){e.preventDefault();const {error}=await supabase.from("groups").insert({name,course,level,capacity:Number(capacity)});if(error)alert(error.message);else await onSaved()}return <Modal title="Guruh yaratish" onClose={onClose}><form onSubmit={save}><FormInput label="Guruh nomi" value={name} onChange={setName} required/><FormSelect label="Kurs" value={course} options={courses.map(c=>[c.name,c.name])} onChange={setCourse}/><FormInput label="Daraja" value={level} onChange={setLevel}/><FormInput label="Sig‘im" type="number" value={capacity} onChange={setCapacity}/><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}}>Guruhni saqlash <Check size={16}/></button></form></Modal>}
function CreateCourse({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState("");const [code,setCode]=useState("");const [duration,setDuration]=useState("6");const [price,setPrice]=useState("0");async function save(e:any){e.preventDefault();const {error}=await supabase.from("courses").insert({name,code:code||null,duration_months:Number(duration),price:Number(price)});if(error)alert(error.message);else await onSaved()}return <Modal title="Kurs qo‘shish" onClose={onClose}><form onSubmit={save}><FormInput label="Kurs nomi" value={name} onChange={setName} required/><FormInput label="Kod" value={code} onChange={setCode}/><FormInput label="Davomiyligi (oy)" type="number" value={duration} onChange={setDuration}/><FormInput label="Narxi" type="number" value={price} onChange={setPrice}/><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}}>Kursni saqlash <Check size={16}/></button></form></Modal>}
function CreatePayment({students,courses,onClose,onSaved}:{students:Student[];courses:Course[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({payment_date:new Date().toISOString().slice(0,10),method:"cash",status:"paid"});async function save(e:any){e.preventDefault();const {error}=await supabase.from("payments").insert({...f,amount:Number(f.amount)});if(error)alert(error.message);else await onSaved()}return <Modal title="To‘lov kiritish" onClose={onClose}><form onSubmit={save}><FormSelect label="O‘quvchi" value={f.student_id||""} options={students.map(s=>[s.id,s.full_name])} onChange={v=>setF({...f,student_id:v})} required/><FormSelect label="Kurs" value={f.course_id||""} options={courses.map(c=>[c.id,c.name])} onChange={v=>setF({...f,course_id:v})}/><FormInput label="Summa" type="number" value={f.amount||""} onChange={v=>setF({...f,amount:v})} required/><FormInput label="Sana" type="date" value={f.payment_date} onChange={v=>setF({...f,payment_date:v})}/><FormSelect label="Usul" value={f.method} options={[["cash","Naqd"],["card","Karta"],["transfer","Transfer"],["online","Online"],["other","Boshqa"]]} onChange={v=>setF({...f,method:v})}/><div className="field"><label>Izoh</label><textarea value={f.note||""} onChange={e=>setF({...f,note:e.target.value})}/></div><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}}>To‘lovni saqlash <Check size={16}/></button></form></Modal>}
function CreateAttendance({students,groups,onClose,onSaved}:{students:Student[];groups:Group[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({attendance_date:new Date().toISOString().slice(0,10),status:"present"});async function save(e:any){e.preventDefault();const {error}=await supabase.from("attendance").upsert(f,{onConflict:"student_id,attendance_date"});if(error)alert(error.message);else await onSaved()}return <Modal title="Davomat kiritish" onClose={onClose}><form onSubmit={save}><FormSelect label="O‘quvchi" value={f.student_id||""} options={students.map(s=>[s.id,s.full_name])} onChange={v=>setF({...f,student_id:v})} required/><FormSelect label="Guruh" value={f.group_id||""} options={groups.map(g=>[g.id,g.name])} onChange={v=>setF({...f,group_id:v})}/><FormInput label="Sana" type="date" value={f.attendance_date} onChange={v=>setF({...f,attendance_date:v})}/><FormSelect label="Holat" value={f.status} options={[["present","Keldi"],["absent","Kelmagan"],["late","Kechikdi"],["excused","Uzrli"]]} onChange={v=>setF({...f,status:v})}/><div className="field"><label>Izoh</label><textarea value={f.note||""} onChange={e=>setF({...f,note:e.target.value})}/></div><button className="btn primary btn-lg" style={{width:"100%",marginTop:18}}>Davomatni saqlash <Check size={16}/></button></form></Modal>}
function FormInput({label,value,onChange,type="text",required=false,placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;placeholder?:string}){return <div className="field" style={{marginTop:12}}><label>{label}</label><input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required} placeholder={placeholder}/></div>};function FormSelect({label,value,options,onChange,required=false}:{label:string;value:string;options:string[][];onChange:(v:string)=>void;required?:boolean}){return <div className="field" style={{marginTop:12}}><label>{label}</label><select value={value} onChange={e=>onChange(e.target.value)} required={required}><option value="">Tanlang...</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}
