"use client";
import { useEffect, useState } from "react";
import { LockKeyhole, Play, Save, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase";

export default function CodeLabPage(){
 const supabase=createClient(); const [loading,setLoading]=useState(true); const [allowed,setAllowed]=useState(false); const [stage,setStage]=useState(1); const [code,setCode]=useState("print('Salom, NOVA!')"); const [output,setOutput]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} const {data}=await supabase.from("feature_access").select("unlocked,stage").eq("student_id",user.id).eq("feature_key","code_lab").maybeSingle(); setAllowed(Boolean(data?.unlocked));setStage(data?.stage||1);setLoading(false);})();},[]);
 if(loading)return <main className="page-loader"><span>Code Lab tekshirilmoqda...</span></main>;
 if(!allowed)return <main className="auth-page"><div className="auth-shell"><div className="auth-card"><LockKeyhole size={42}/><div className="eyebrow">NOVA CODE LAB</div><h2>Funksiya hali yopiq</h2><p className="muted">Siz hozircha ushbu laboratoriyaga kira olmaysiz. Kerakli bosqichga yetganingizdan so‘ng administrator ruxsat beradi.</p><div className="reward-banner"><ShieldCheck size={20}/><div><strong>Admin tasdig‘i kerak</strong><span>O‘qituvchingiz bilan bog‘laning.</span></div></div><a className="btn" href="/dashboard">Dashboard'ga qaytish</a></div></div></main>;
 return <main className="crm-page"><header className="crm-nav"><div className="crm-brand"><a className="logo" href="/">NOVA <span>ACADEMY</span></a><b>CODE LAB</b></div><span className="tag">Stage {stage} unlocked</span></header><section className="crm-content"><div className="crm-title"><div><div className="eyebrow">INTERACTIVE LEARNING</div><h1>NOVA Code Lab.</h1><p className="muted">Kod yozing, ishga tushiring va topshiriqni bajaring.</p></div></div><div className="crm-grid-two"><div className="crm-panel"><h3>Editor</h3><textarea value={code} onChange={e=>setCode(e.target.value)} style={{width:"100%",minHeight:300,fontFamily:"monospace"}}/><button className="btn primary" onClick={()=>setOutput(code.includes("print")?code.match(/print\(['"](.*?)['"]\)/)?.[1]||"Kod bajarildi":"Demo: kod saqlandi")}><Play size={15}/> Run</button><button className="btn" onClick={()=>localStorage.setItem("nova-code",code)}><Save size={15}/> Saqlash</button></div><div className="crm-panel"><h3>Output</h3><pre>{output||"Natija shu yerda ko‘rinadi..."}</pre></div></div></section></main>;
}
